name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches: [ main ]   # Ejecuta al subir cambios a la rama 'main' (ajusta si usas otra)

permissions:
  contents: read         # Permiso de lectura del repo (para checkout)
  pages: write           # Necesario para publicar en GitHub Pages
  id-token: write        # Requisito para autenticación OIDC en despliegue

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4    # Trae el código del repo al runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'     # Versión de Python del runner

      # Instala MkDocs y el tema Material
      # Si tienes requirements.txt, sustituye por: pip install -r requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Construye el sitio en la carpeta 'site'
      - name: Build MkDocs site
        run: mkdocs build --strict

      # Sube el sitio construido como artefacto para Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # Despliega en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4